// <auto-generated />
using EFCoreTest1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EFCoreTest1.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20180704185904_init-database")]
    partial class initdatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreTest1.Domain.Afspraak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BeginDatum");

                    b.HasKey("Id");

                    b.ToTable("Afspraken");
                });

            modelBuilder.Entity("EFCoreTest1.Domain.Afspraak", b =>
                {
                    b.OwnsOne("EFCoreTest1.Domain.AdresAfspraak", "Adres", b1 =>
                        {
                            b1.Property<int>("AfspraakId");

                            b1.Property<string>("Straat");

                            b1.ToTable("Afspraken");

                            b1.HasOne("EFCoreTest1.Domain.Afspraak")
                                .WithOne("Adres")
                                .HasForeignKey("EFCoreTest1.Domain.AdresAfspraak", "AfspraakId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsOne("EFCoreTest1.Domain.HuisnummerType", "Huisnummer", b2 =>
                                {
                                    b2.Property<int>("AdresAfspraakAfspraakId");

                                    b2.Property<int>("Nummer");

                                    b2.Property<string>("Toevoeging");

                                    b2.ToTable("Afspraken");

                                    b2.HasOne("EFCoreTest1.Domain.AdresAfspraak")
                                        .WithOne("Huisnummer")
                                        .HasForeignKey("EFCoreTest1.Domain.HuisnummerType", "AdresAfspraakAfspraakId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
